[book]
authors = ["ritchie46"]
language = "en"
multilingual = false
src = "src"
title = "polars-book"

[output.html]
default-theme = "Ayu"
mathjax-support = true

#[output.linkcheck] # validate links

[output.html.fold]
# toggle this to fold side tabs
enable = true
level = 1
